# Generated by Django 6.0 on 2026-04-26 07:01

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.Profile._avatar_upload_path),
        ),
    ]
